##### 公用默认配置 #####

defaults:
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-05
  learning_rate: 1.0e-06
  min_learning_rate: 1.0e-07
  lr_decay_ratio: 1.0
  lr_decay_steps: 0
  warmup_max_lr: 0.0001
  warmup_min_lr: 1.0e-09
  warmup_ratio: 0.001
  warmup_steps: 0
  weight_decay: 0.1
  scheduler_type: cosine

data:
  prefix: 
    model: "<bot>:"
    human: "<human>:"
  multiturn_seperator: "\n"  

policy_model:
  policy_model_type: null
  policy_tokenizer_path: null
  policy_model_path: null
  policy_max_seq_len: 2048

reward_model:
  reward_model_type: null
  rm_tokenizer_path: null
  reward_model_path: null
  rm_max_seq_len: 2048