##### 流程配置 #####
pipeline:
  policy_model_type: "llama_13B"
  pipeline:
    - prepare
    - edpo
  prepare_list:
    - policy
  dataset_path: "/cognitive_comp/wanghao/data/processed_data/edpo_dataset_poem_10_0808.jsonl"
  workspace_path: "/cognitive_comp/wanghao/workspace/pipeline"
  logging_level: info ### debug, info, warning, error
  enable_flops_profiler: false
  gpus: 4
  
##### 细节配置（可选） #####
logger:
  wandb_project: "EDPO_LLAMA13B_poem"
  wandb_name: "pipeline"
  wandb_group: ""
  wandb_team: "yukawa"

data:
  prefix: 
    model: "<bot>:"
    human: "<human>:"
  multiturn_seperator: "\n"  

megatron:
  deepspeed_stage: 1
  offload_optimizer: true
  tensor_model_parallel_size: 4
  pipe_model_parallel_size: 1
  seed: 42


policy_model:
  policy_model_type: "llama_13B"
  policy_tokenizer_path: null
  policy_model_path: null
  policy_max_seq_len: 1000

edpo:
  experience:
    experience_batch_size: 1
    generate_minibatch_size: 1
    policy_minibatch_size: 1
    sample_batch_size: 1
  trainer:
    actor_lr: 2.0e-06
    policy_train_batch_size: 1
  edpo_details:
    dpo_beta:                   0.5                                                                                   
    edpo_preference_batch_size: 1                                                                                     
    save_every_n_episode:       50                                                                                                
